// This is a machine-generated code: Do not modify.
// Scripted by: Mohammad Mottaghi (mamad [a^t] cs.duke.edu)
// Generated on: Monday, 9/5/2016 5:25:16 PM


enum enTagIdentity
{
  iNoTag = 0,
  itagHTML = 1<<0,
  itagHead = 1<<1,
  itagBody = 1<<2,
  itagP = 1<<3,
  itagA = 1<<4,
  itagButton = 1<<5,
  itagLi = 1<<6,
  itagForm = 1<<7,
  itagTable = 1<<8,
  itagTr = 1<<9,
  itagSelect = 1<<10,
  itagOption = 1<<11,
  itagOptgroup = 1<<12,
  icComment = 1<<13,
  icSelectIgnored = 1<<14,
  icCloseSelect = 1<<15,
  icTableTunl = 1<<16,
  icVoid = 1<<17,
  icPseudoVoid = 1<<18,
  icTableTags = 1<<19,
  icTbleDirectTags = 1<<20,
  icTableCells = 1<<21,
  icTableCol = 1<<22,
  icTableNoCol = 1<<23,
  icCloseP = 1<<24,
  icDefiners = 1<<25,
  icHeadings = 1<<26,
  icScrStyl = 1<<27,
  icHeadTags = 1<<28,
  igTerminal = icVoid | icPseudoVoid,
  igComboTags = itagOption | itagOptgroup,
};

enum enTagIdentifier
{ // Do NOT reorder
  tiNil, 
  tiRoot,   // this is a virutal tag, introduced and used by the parser
  tiComment, 
  tiDocType, 
  tiCustomTag,   // e.g.  <my-tag>  as opposed to HTML tags such as <p>, <div>, <ul> …
  tiHtml, 
  tiHead, 
  tiBody, 
  tiCaption, 
  tiTd, 
  tiTh, 
  tiCol, 
  tiColgroup, 
  tiTbody, 
  tiTfoot, 
  tiThead, 
  tiTr, 
  tiTable, 
  tiSelect, 
  tiP, 
  tiDd, 
  tiDt, 
  tiH1, 
  tiH2, 
  tiH3, 
  tiH4, 
  tiH5, 
  tiH6, 
  tiLi, 
  tiButton, 
  tiA, 
  tiOption, 
  tiOptgroup, 
  tiObject, 
  tiForm, 
  tiDetails, 
  tiArticle, 
  tiAside, 
  tiBlockquote, 
  tiDl, 
  tiFieldset, 
  tiFigcaption, 
  tiFigure, 
  tiFooter, 
  tiHeader, 
  tiHgroup, 
  tiNav, 
  tiOl, 
  tiPre, 
  tiSection, 
  tiSummary, 
  tiUl, 
  tiMenu, 
  tiMenuitem, 
  tiAbbr, 
  tiAddress, 
  tiAudio, 
  tiBdi, 
  tiBdo, 
  tiCanvas, 
  tiCite, 
  tiDatalist, 
  tiDel, 
  tiDfn, 
  tiDiv, 
  tiDialog, 
  tiIns, 
  tiKbd, 
  tiLabel, 
  tiLegend, 
  tiMap, 
  tiMark, 
  tiMeter, 
  tiOutput, 
  tiProgress, 
  tiQ, 
  tiRp, 
  tiRt, 
  tiRuby, 
  tiSamp, 
  tiSpan, 
  tiSub, 
  tiSup, 
  tiTime, 
  tiVar, 
  tiVideo, 
  tiB, 
  tiCode, 
  tiEm, 
  tiI, 
  tiS, 
  tiSmall, 
  tiStrong, 
  tiU, 
  tiArea, 
  tiBase, 
  tiBr, 
  tiCommand, 
  tiEmbed, 
  tiHr, 
  tiImg, 
  tiInput, 
  tiKeygen, 
  tiLink, 
  tiMeta, 
  tiParam, 
  tiSource, 
  tiTrack, 
  tiWbr, 
  tiIframe, 
  tiNoscript, 
  tiScript, 
  tiStyle, 
  tiTextarea, 
  tiTitle, 
};
